- name: Update CouchDB masternode url
  become: yes
  replace:
    dest: /home/ubuntu/project/assignment2-comp90024/Harvester_T/.envdb
    regexp: 'http:\/\/[0-9]+(?:\.[0-9]+){3}:[0-9]+'
    replace: "http://{{groups['masternode'][0]}}:{{couchdb_port}}"

- name: Build docker image
  become: yes
  command: 'docker build -f Dockerfile.bulkHarvestor -t bulk_harvestor .'
  args:  
    chdir: /home/ubuntu/project/assignment2-comp90024/Harvester_T

- name: Run docker image
  become: yes
  command: docker run -d bulk_harvestor
  