- name: Create CouchDB User
  become: yes
  user:
    name: couchdb
    password: couchdb
    comment: "CouchDB System Account"
    shell: /bin/bash
    system: yes
    home: /data/couchdb
    createhome: no

- name: Create directory for to be mapped into container
  become: yes
  file:
    path: /data/couchdb
    owner: couchdb
    group: couchdb
    mode: 0770
    recurse: yes
    state: directory

- name: Create directory for couchdb .ini file
  become: yes
  file:
    path: /data/couchdb/etc
    owner: couchdb
    group: couchdb
    mode: 0644
    recurse: yes
    state: directory

- name: Copy local.ini file to each instance
  become: yes
  copy:
    src: "files/local.ini"
    dest: "/data/couchdb/etc/"
    mode: 0600


- name: Start a container with a couchdb
  become: yes
  docker_container:
    name: "{{ couchdb_container_name}}"
    image: "{{ couchdb_image }}"
    ports:
      - "{{couchdb_port}}:{{couchdb_port}}"
      - "{{erlang_port}}:{{erlang_port}}"
      - "{{cluster_com_port}}:{{cluster_com_port}}"
    volumes:
      - /data/couchdb/etc:/opt/couchdb/etc/local.d
    env:
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      NODENAME: "{{ ansible_host }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"